"""
Django settings for statementautomation project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%#tr$(v7cy#%a*@tp_!j4dee56k-p7=6=n^qu-pjp76##n65c4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [

    'bangkok-hostels-slowly-gender.trycloudflare.com',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://bangkok-hostels-slowly-gender.trycloudflare.com',
]


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_simple_bulma',
    'django.contrib.staticfiles',
    'simple_history',
    'compliance',
    'import_export',
    'django_filters',
    'django_tables2',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'statementautomation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [                    BASE_DIR / 'templates',  # This is where your templates folder is
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'statementautomation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Static files settings
STATIC_URL = '/static/'

# Location where collectstatic will copy all static files
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Optional: Additional static file directories (if you're using custom ones)
# STATICFILES_DIRS = [
#     BASE_DIR / 'your_custom_static_dir',
# ]

# Use WhiteNoise to serve compressed and cached static files (in production)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Static files finders
STATICFILES_FINDERS = [
    # Default static file finders
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    # Add SimpleBulmaFinder to ensure Bulma assets are found by collectstatic
    'django_simple_bulma.finders.SimpleBulmaFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom settings for django-simple-bulma
# Custom settings for django-simple-bulma
BULMA_SETTINGS = {
  "extensions": [
    "all",  # Includes all Bulma extensions for flexibility
    "bulma-calendar",
  ],
  "variables": {
    # Vibrant and accessible color palette (WCAG AA compliant)
    "primary": "#2563eb",         # Vibrant blue
    "link": "#10b981",            # Emerald green
    "info": "#3b82f6",            # Info blue
    "success": "#22c55e",         # Lime green
    "warning": "#f59e0b",         # Amber
    "danger": "#ef4444",          # Red

    # Background and contrast
    "scheme-main": "#ffffff",     # Light background
    "scheme-invert": "#111827",   # Deep gray/black for contrast

    # Typography sizing
    "size-1": "4rem",             # Slightly smaller than before for balance
  },
  "alt_variables": {
    # Dark mode theme with strong contrast
    "primary": "#ffffff",         # White for primary elements
    "scheme-main": "#1e293b",     # Slate dark background
    "scheme-invert": "#ffffff",   # Light text
  },
  "output_style": "compressed",  # Minify output for performance
}
