# Generated by Django 5.1.7 on 2025-03-29 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_date', models.DateField()),
                ('last_reviewed_date', models.DateField()),
                ('last_tested_date', models.DateField()),
                ('tested_by', models.CharField(max_length=200)),
                ('feedback_header', models.TextField()),
                ('reporting_problems_text', models.TextField()),
                ('enforcement_procedure', models.TextField()),
                ('legal_compliance_text', models.TextField()),
                ('legal_wording_present', models.BooleanField(default=True)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('partially', 'Partially Compliant'), ('non_compliant', 'Non-Compliant')], max_length=20)),
                ('wcag_version', models.CharField(max_length=50)),
                ('feedback_email', models.EmailField(max_length=254)),
                ('feedback_phone', models.CharField(max_length=20)),
                ('reporting_email', models.EmailField(max_length=254)),
                ('reporting_phone', models.CharField(max_length=20)),
                ('non_accessible_content', models.TextField()),
                ('report_run_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=200)),
                ('item_text', models.TextField()),
                ('item_url', models.URLField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compliance.compliancereport')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_url', models.URLField()),
                ('statement_url', models.URLField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='compliance.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='compliance.product'),
        ),
    ]
