# Generated by Django 5.1.7 on 2025-03-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_remove_compliancereportitem_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='portfolio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='compliance.portfolio'),
        ),
        migrations.AddField(
            model_name='report',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='compliance.portfolio'),
        ),
    ]
