# Generated by Django 5.1.7 on 2025-04-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_historicalreport_enforcement_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreport',
            name='statement_compliance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='statement_compliance',
            field=models.BooleanField(default=False),
        ),
    ]
