# Generated by Django 5.1.7 on 2025-04-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_historicalreport_statement_compliance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreport',
            name='legal_wording_not_present',
        ),
        migrations.RemoveField(
            model_name='report',
            name='legal_wording_not_present',
        ),
    ]
