# Generated by Django 5.1.7 on 2025-04-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_portfolio_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_status',
            new_name='statement_url_status',
        ),
    ]
