# Generated by Django 5.1.7 on 2025-04-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_rename_url_status_product_statement_url_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreport',
            name='days_since_last_tested',
        ),
        migrations.RemoveField(
            model_name='report',
            name='days_since_last_tested',
        ),
    ]
